/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cambiaventas;

import static cambiaventas.Main.IPSUCURSAL;
import static cambiaventas.Main.sucursalnombre;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;

/**
 *
 * @author agonzalez
 */
public class MenuAvanzado extends javax.swing.JFrame {

    /**
     * Creates new form MenuAvanzado
     */
    public MenuAvanzado() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/recursos/logochico.png")).getImage());
        txtsucursal.setText("" + sucursalnombre);
        txtsucursal.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtsucursal = new javax.swing.JLabel();
        btnlistacodigos = new javax.swing.JButton();
        btncargaperiodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Avanzado");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Conectado a:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 30));

        txtsucursal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsucursal.setForeground(new java.awt.Color(0, 51, 204));
        txtsucursal.setText(" ");
        getContentPane().add(txtsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 170, 30));

        btnlistacodigos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnlistacodigos.setText("Correr Lista codigos");
        btnlistacodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistacodigosActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistacodigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 270, 50));

        btncargaperiodo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btncargaperiodo.setText("Correr carga periodo dos meses");
        btncargaperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargaperiodoActionPerformed(evt);
            }
        });
        getContentPane().add(btncargaperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 270, 50));

        jLabel1.setText("     ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 324, -1, 20));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 270, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistacodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistacodigosActionPerformed
        listacodigostmp();

    }//GEN-LAST:event_btnlistacodigosActionPerformed
    public void cargaperiododosmeses() {
        //**************PROGRESSS BAR
        String cval;
        int nval;

        final JDialog dialog = new JDialog(Frame.getFrames()[0], "Sistema de actualiza ventas", true);
        Thread runnable_progress = new Thread() {
            public void run() {
                JTextArea msgLabel;
                JProgressBar progressBar;
                final int MAXIMUM = 100;
                JPanel panel;
                progressBar = new JProgressBar(0, MAXIMUM);
                progressBar.setIndeterminate(true);
                msgLabel = new JTextArea("Ejecutando Periodo dos meses. Por favor espere...");
                msgLabel.setEditable(false);
                panel = new JPanel(new BorderLayout(5, 5));
                panel.add(msgLabel, BorderLayout.PAGE_START);
                panel.add(progressBar, BorderLayout.CENTER);
                panel.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));
                dialog.getContentPane().add(panel);
                dialog.setResizable(false);
                dialog.pack();
                dialog.setSize(500, dialog.getHeight());
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.setAlwaysOnTop(false);
                msgLabel.setBackground(panel.getBackground());
                ///////////////////////        
                int nren;
                ///////////PROGRESSSBARRRR
               try {
                    System.out.println("809");
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
                    java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://" + IPSUCURSAL + "", "usounds", "madljda");
                    Statement st = conexion.createStatement();

                    ResultSet rs = st.executeQuery("cml.dbo.spp_CargaPeriodosDosMeses");

                    int c = 0;
                    while (!(rs.isAfterLast())) {
                        System.out.println("##" + rs.next() + " >" + c);
                        c = c + 1;
                    }

                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    String respuesta = "The executeQuery method must return a result set.";
                    if (respuesta.equals(e.getMessage())) {
                        progressBar.setIndeterminate(false);///PROGRESSBAR
                        dialog.dispose();//PROGRESSBAR
                      JOptionPane.showMessageDialog(null, "Se ha corrido Carga periodo dos meses correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                listacredito();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR!!!!!!!" + e.getMessage());
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAvanzado.class.getName()).log(Level.SEVERE, null, ex);
                }

                nren = 0;

                ///////////////////////
            }
        };
        ///PROGRESSBAR>
        runnable_progress.start();
        dialog.setVisible(true);
        //<PROGRESSBAR

    }
    private void btncargaperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargaperiodoActionPerformed
      cargaperiododosmeses();
    }//GEN-LAST:event_btncargaperiodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void listacodigostmp() {
        //**************PROGRESSS BAR
        String cval;
        int nval;

        final JDialog dialog = new JDialog(Frame.getFrames()[0], "Sistema de actualiza ventas", true);
        Thread runnable_progress = new Thread() {
            public void run() {
                JTextArea msgLabel;
                JProgressBar progressBar;
                final int MAXIMUM = 100;
                JPanel panel;
                progressBar = new JProgressBar(0, MAXIMUM);
                progressBar.setIndeterminate(true);
                msgLabel = new JTextArea("Procesando listacodigostpm. Por favor espere...");
                msgLabel.setEditable(false);
                panel = new JPanel(new BorderLayout(5, 5));
                panel.add(msgLabel, BorderLayout.PAGE_START);
                panel.add(progressBar, BorderLayout.CENTER);
                panel.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));
                dialog.getContentPane().add(panel);
                dialog.setResizable(false);
                dialog.pack();
                dialog.setSize(500, dialog.getHeight());
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.setAlwaysOnTop(false);
                msgLabel.setBackground(panel.getBackground());
                ///////////////////////        
                int nren;
                ///////////PROGRESSSBARRRR
               try {
                    System.out.println("809");
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
                    java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://" + IPSUCURSAL + "", "usounds", "madljda");
                    Statement st = conexion.createStatement();

                    ResultSet rs = st.executeQuery(" cml.dbo.spp_ListaCodigosTmp");

                    int c = 0;
                    while (!(rs.isAfterLast())) {
                        System.out.println("##" + rs.next() + " >" + c);
                        c = c + 1;
                    }

                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    String respuesta = "The executeQuery method must return a result set.";
                    if (respuesta.equals(e.getMessage())) {
                        progressBar.setIndeterminate(false);///PROGRESSBAR
                        dialog.dispose();//PROGRESSBAR
                   //     JOptionPane.showMessageDialog(null, "Se ha corrido listacodigos", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                listacredito();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR!!!!!!!" + e.getMessage());
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAvanzado.class.getName()).log(Level.SEVERE, null, ex);
                }

                nren = 0;

                ///////////////////////
            }
        };
        ///PROGRESSBAR>
        runnable_progress.start();
        dialog.setVisible(true);
//<PROGRESSBAR

    }

    public void listacredito() {
        //**************PROGRESSS BAR
        String cval;
        int nval;

        final JDialog dialog = new JDialog(Frame.getFrames()[0], "Sistema de actualiza ventas", true);
        Thread runnable_progress = new Thread() {
            public void run() {
                JTextArea msgLabel;
                JProgressBar progressBar;
                final int MAXIMUM = 100;
                JPanel panel;
                progressBar = new JProgressBar(0, MAXIMUM);
                progressBar.setIndeterminate(true);
                msgLabel = new JTextArea("Procesando listacredito. Por favor espere...");
                msgLabel.setEditable(false);
                panel = new JPanel(new BorderLayout(5, 5));
                panel.add(msgLabel, BorderLayout.PAGE_START);
                panel.add(progressBar, BorderLayout.CENTER);
                panel.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));
                dialog.getContentPane().add(panel);
                dialog.setResizable(false);
                dialog.pack();
                dialog.setSize(500, dialog.getHeight());
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.setAlwaysOnTop(false);
                msgLabel.setBackground(panel.getBackground());
                ///////////////////////        

                int nren;

        ///////////PROGRESSSBARRRR
                System.out.println("808" + IPSUCURSAL);
                try {
                    System.out.println("809");
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
                    java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://" + IPSUCURSAL + "", "usounds", "madljda");
                    Statement st = conexion.createStatement();

                    ResultSet rs = st.executeQuery(" cml.dbo.spp_ListaCodigosCredito "
                    );

                    int c = 0;
                    while (!(rs.isAfterLast())) {
                        System.out.println("##" + rs.next() + " >" + c);
                        c = c + 1;
                    }

                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    String respuesta = "The executeQuery method must return a result set.";
                    if (respuesta.equals(e.getMessage())) {
                        progressBar.setIndeterminate(false);///PROGRESSBAR
                        dialog.dispose();//PROGRESSBAR
                     //   JOptionPane.showMessageDialog(null, "Se ha corrido lista credito", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        listacodigoapartados();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR!!!!!!!" + e.getMessage());
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAvanzado.class.getName()).log(Level.SEVERE, null, ex);
                }

                nren = 0;

                ///////////////////////
            }
        };
        ///PROGRESSBAR>
        runnable_progress.start();
        dialog.setVisible(true);
//<PROGRESSBAR

    }

    public void listacodigoapartados() {
        //**************PROGRESSS BAR
        String cval;
        int nval;

        final JDialog dialog = new JDialog(Frame.getFrames()[0], "Sistema de actualiza ventas", true);
        Thread runnable_progress = new Thread() {
            public void run() {
                JTextArea msgLabel;
                JProgressBar progressBar;
                final int MAXIMUM = 100;
                JPanel panel;
                progressBar = new JProgressBar(0, MAXIMUM);
                progressBar.setIndeterminate(true);
                msgLabel = new JTextArea("Procesando lista codigo apartados. Por favor espere...");
                msgLabel.setEditable(false);
                panel = new JPanel(new BorderLayout(5, 5));
                panel.add(msgLabel, BorderLayout.PAGE_START);
                panel.add(progressBar, BorderLayout.CENTER);
                panel.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));
                dialog.getContentPane().add(panel);
                dialog.setResizable(false);
                dialog.pack();
                dialog.setSize(500, dialog.getHeight());
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.setAlwaysOnTop(false);
                msgLabel.setBackground(panel.getBackground());
                ///////////////////////        

                int nren;

                ///////////PROGRESSSBARRRR
                try {
                    System.out.println("809");
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
                    java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://" + IPSUCURSAL + "", "usounds", "madljda");
                    Statement st = conexion.createStatement();

                    ResultSet rs = st.executeQuery(" cml.dbo.spp_ListaCodigosApartados");
                    System.out.println("810");

                    int c = 0;
                    while (!(rs.isAfterLast())) {
                        System.out.println("##" + rs.next() + " >" + c);
                        c = c + 1;
                    }

                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    String respuesta = "The executeQuery method must return a result set.";
                    if (respuesta.equals(e.getMessage())) {
                        progressBar.setIndeterminate(false);///PROGRESSBAR
                        dialog.dispose();//PROGRESSBAR
                       // JOptionPane.showMessageDialog(null, "Se ha corrido lista codigos apartados", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                         listacodigosusadoscompra();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR!!!!!!!" + e.getMessage());
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAvanzado.class.getName()).log(Level.SEVERE, null, ex);
                }

                nren = 0;

                ///////////////////////
            }
        };
        ///PROGRESSBAR>
        runnable_progress.start();
        dialog.setVisible(true);
//<PROGRESSBAR

    }

    public void listacodigosusadoscompra() {
        //**************PROGRESSS BAR
        String cval;
        int nval;

        final JDialog dialog = new JDialog(Frame.getFrames()[0], "Sistema de actualiza ventas", true);
        Thread runnable_progress = new Thread() {
            public void run() {
                JTextArea msgLabel;
                JProgressBar progressBar;
                final int MAXIMUM = 100;
                JPanel panel;
                progressBar = new JProgressBar(0, MAXIMUM);
                progressBar.setIndeterminate(true);
                msgLabel = new JTextArea("Procesando lista CodigosUsadosCompraTmp. Por favor espere...");
                msgLabel.setEditable(false);
                panel = new JPanel(new BorderLayout(5, 5));
                panel.add(msgLabel, BorderLayout.PAGE_START);
                panel.add(progressBar, BorderLayout.CENTER);
                panel.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));
                dialog.getContentPane().add(panel);
                dialog.setResizable(false);
                dialog.pack();
                dialog.setSize(500, dialog.getHeight());
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.setAlwaysOnTop(false);
                msgLabel.setBackground(panel.getBackground());
                ///////////////////////        

                int nren;

                System.out.println("808" + IPSUCURSAL);
                try {
                    System.out.println("809");
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
                    java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://" + IPSUCURSAL + "", "usounds", "madljda");
                    Statement st = conexion.createStatement();

                    ResultSet rs = st.executeQuery(" cml.dbo.spp_ListaCodigosUsadosCompraTmp"
                    );

                    int c = 0;
                    while (!(rs.isAfterLast())) {
                        System.out.println("##" + rs.next() + " >" + c);
                        c = c + 1;
                    }

                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    String respuesta = "The executeQuery method must return a result set.";
                    if (respuesta.equals(e.getMessage())) {
                        progressBar.setIndeterminate(false);///PROGRESSBAR
                        dialog.dispose();//PROGRESSBAR
                       // JOptionPane.showMessageDialog(null, "Se ha corrido lista codigos usados compra", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                listacodigosusadosventa();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR!!!!!!!" + e.getMessage());
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAvanzado.class.getName()).log(Level.SEVERE, null, ex);
                }

                nren = 0;
                ///////////////////////
            }
        };
        ///PROGRESSBAR>
        runnable_progress.start();
        dialog.setVisible(true);
//<PROGRESSBAR

    }

    public void listacodigosusadosventa() {
        //**************PROGRESSS BAR
        String cval;
        int nval;

        final JDialog dialog = new JDialog(Frame.getFrames()[0], "Sistema de actualiza ventas", true);
        Thread runnable_progress = new Thread() {
            public void run() {
                JTextArea msgLabel;
                JProgressBar progressBar;
                final int MAXIMUM = 100;
                JPanel panel;
                progressBar = new JProgressBar(0, MAXIMUM);
                progressBar.setIndeterminate(true);
                msgLabel = new JTextArea("Procesando lista codigosusadosventa. Por favor espere...");
                msgLabel.setEditable(false);
                panel = new JPanel(new BorderLayout(5, 5));
                panel.add(msgLabel, BorderLayout.PAGE_START);
                panel.add(progressBar, BorderLayout.CENTER);
                panel.setBorder(BorderFactory.createEmptyBorder(11, 11, 11, 11));
                dialog.getContentPane().add(panel);
                dialog.setResizable(false);
                dialog.pack();
                dialog.setSize(500, dialog.getHeight());
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.setAlwaysOnTop(false);
                msgLabel.setBackground(panel.getBackground());
                ///////////////////////        
                int nren;

           ///////////PROGRESSSBARRRR
                System.out.println("808" + IPSUCURSAL);
                try {
                    System.out.println("809");
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
                    java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://" + IPSUCURSAL + "", "usounds", "madljda");
                    Statement st = conexion.createStatement();

                    ResultSet rs = st.executeQuery("cml.dbo.spp_ListaCodigosUsadosVentaTmp");

                    int c = 0;
                    while (!(rs.isAfterLast())) {
                        System.out.println("##" + rs.next() + " >" + c);
                        c = c + 1;
                    }

                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    String respuesta = "The executeQuery method must return a result set.";
                    if (respuesta.equals(e.getMessage())) {
                        progressBar.setIndeterminate(false);///PROGRESSBAR
                        dialog.dispose();//PROGRESSBAR
                        JOptionPane.showMessageDialog(null, "Se ha finalizado el proceso", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR!!!!!!!" + e.getMessage());
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuAvanzado.class.getName()).log(Level.SEVERE, null, ex);
                }
                nren = 0;
            }
        };
        ///PROGRESSBAR>
        runnable_progress.start();
        dialog.setVisible(true);
        //<PROGRESSBAR
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAvanzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargaperiodo;
    private javax.swing.JButton btnlistacodigos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txtsucursal;
    // End of variables declaration//GEN-END:variables
}
